name: Build and Deploy Vue to Pages

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5 # 👈 升级到 v5

      - name: Set up Node.js
        uses: actions/setup-node@v5 # 👈 升级到 v5
        with:
          node-version: 20 # 这里是你项目的 Node 版本，保持不变即可
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5 # 👈 升级到 v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 暂无新版可不改，或用下方环境变量解决
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 暂无新版可不改，或用下方环境变量解决
