name: Build and Push Dist to Org Repo

on:
  push:
    branches: ['main']

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Push to pandaled-biexi-com-ffdjjk/website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 如果要A仓库在workflow中操作B仓库,就得在B仓库所属的User里拿到token,放在A仓库的Repository secrets,这样A仓库才有权限操作B仓库.
          ## B: User-Settings-Developer Settings-Personal access tokens-Tokens(classic)-Generate new token(classic)-获取密码
          ## A: Repository-Settings-Secrets and variables-Actions-Repository secrets-添加为变量如ORG_DEPLOY_TOKEN
          token: ${{ secrets.ORG_DEPLOY_TOKEN }}
          repository-name: pandaled-biexi-com-ffdjjk/website
          branch: main
          folder: dist
          clean: true
          single-commit: true
